### ISSUE TITLE
Loading capistrano before setting application name breaks

### ISSUE THREAD

**Issue by KieranP** [DataDog/dogapi-rb#149] opened 2018-04-09 02:48 UTC
Should be able to load capistrano datadog before setting name, as common practice is to put all require lines at the top of files before the `set` commands. However:

**Loading before name set**

```ruby
require "capistrano/datadog"
set :application, "app"
```

```
triggering load callbacks
Please specify the name of your application, set :application, 'foo'
```

**Loading after name set**

```ruby
set :application, "app"
require "capistrano/datadog"
```

```
triggering load callbacks
* 2018-04-09 14:47:44 executing `app'
```

**Comment by zippolyte** [comment] 2020-01-30 10:31
Hey @KieranP 

I couldn't reproduce this issue with the latest version `1.38` of dogapi-rb. Is it still happening for you ?

I tried with a sample capistrano project, with the `deploy.rb` looking like so 
```ruby
require "capistrano/datadog"

set :application, "my_app_name"
set :repo_url, "git@example.com:me/my_repo.git"
set :datadog_api_key, "xxx"
```
and `cap staging deploy` executed fine.

Closing in the meantime, feel free to reopen and provide more details on how to reproduce if this happens again.

Thanks

**Closed by zippolyte** 2020-01-30 10:31 UTC
